### ISSUE TITLE
summer2winter dataset not producing results 

### ISSUE THREAD

**Issue by anish9** [clovaai/tunit#10]
I have two folder summer and winter and i have modified dataset structure as per guidelines(like animal_faces), I started supervised approach since I have proper labelled dataset,  after the successful completion of training for 200 epochs the results are same as original input image with some noises added to it. not sure where the things are going wrong.  how to solve this??

**Comment by FriedRonaldo** [comment]
Hi, the structure of AnimalFaces cannot be directly applied to summer2winter. Because the code might not read the data as your intention.

In this case, please check if the image and label are read as you intended and also check if you set args.output_k to 2.

The directory I used is like:
summer2winter
- train
  - summer
  - winter
- test
  - summer
  - winter

I am sorry for insufficient direction for summer2winter. 
 And please check the intermediate results. It might go bad with too many iterations because it is based on GANs.

---
EDIT
I did not notice that the pre-trained weight of the models trained on summer2winter was not uploaded. I will upload the files today (This is about 01:00 a.m. so it might take 10 hours)

**Comment by anish9** [comment]
I tried the same, but didn't work, got:
`Traceback (most recent call last):
  File "main.py", line 525, in <module>
    main()
  File "main.py", line 201, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 283, in main_worker
    validationFunc(val_loader, networks, 0, args, {'logger': logger, 'queue': queue})
  File "/home/mia/anish/experiments/tunit/validation/validation.py", line 49, in validateUN
    is_best = cluster_eval(args, C, val_loader, val_loader)
  File "/home/mia/anish/experiments/tunit/validation/cluster_eval.py", line 175, in cluster_eval
    mapping_test_dataloader=mapping_test_dataloader)
  File "/home/mia/anish/experiments/tunit/validation/cluster_eval.py", line 86, in cluster_subheads_eval
    reordered_preds[flat_predss_all == pred_i] = torch.tensor(target_i).cuda(int(args.gpu))
RuntimeError: expected dtype Int but got dtype Long`

**Comment by FriedRonaldo** [comment]
I tried run the code, it works well. Did you check the directory of the dataset exactly? I cannot reproduce the error you mentioned.

Please check the intermediate results - it can get worse while the training. The hyperparameter (total epoch) is optimal for AnimalFaces.
