### ISSUE TITLE
I trained to 65 epochs and found an error：“fid_ema, fid_ema_mean is not defined”

### ISSUE THREAD

**Issue by xzq-hnu** [clovaai/tunit#32]
I trained to 65 epochs and found an error：“fid_ema, fid_ema_mean is not defined”

**Comment by FriedRonaldo** [comment]
Is this error raised at https://github.com/clovaai/tunit/blob/master/main.py#L328?

**Comment by xzq-hnu** [comment]
yes，I defined a global variable and tried to modify it, but it didn't work

**Comment by FriedRonaldo** [comment]
And which dataset did you use?

**Comment by xzq-hnu** [comment]
I am using the Afhq_cat dataset, thank you very much for your prompt reply!

**Comment by FriedRonaldo** [comment]
Well, the line https://github.com/clovaai/tunit/blob/master/main.py#L325 was the issue. I changed the code from "'[ffhq', 'lsun_car'] into ['ffhq', 'lsun_car', 'afhq_cat', 'afhq_dog', 'afhq_wild']. 

When I combined the multiple codes, I made a mistake. I am sorry for that.

It will work well and not calculate the FID score (because FID calculation for unsupervised datasets does not properly measure the performance.)

**Comment by xzq-hnu** [comment]
So is it because of a problem with the dataset? Or am I able to solve it without calculating the FID?I've just started working on this, and the question may be stupid.Please excuse me

**Comment by FriedRonaldo** [comment]
> So is it because of a problem with the dataset? 

No, it is just because of the error in the code. With the modification in L325 (I committed the new version in this repository.), it will work. 

> Or am I able to solve it without calculating the FID?

Yes, in other words, the problem can be solved by disabling the FID calculation. (changing L325 is to disable the FID calculation.)

**Comment by xzq-hnu** [comment]
I really appreciate your help and sorry to bother you so much time.

**Comment by FriedRonaldo** [comment]
I also thank you for noticing the error in the code. If there is another problem, feel free to open a new issue.
